### PR TITLE
Nette 3

### PR DESCRIPTION
**Pull request by vojtechmares**
Updated Nette packages to `3.0-dev`

Edit: The PHPStan error is not caused by the change, but I will take a deeper look anyway

### CODE REVIEW

**Comment by f3l1x** [comment]
👍

**Comment by mabar** [comment]
Phpstan failed due to autoloading. Package depends on nette/di 3.0 but phpstan is intalled with 2.4 as 3.0 is not stable. So there are two incompatible versions of same class loaded. One used by phpstan and one loaded for analysis.
@f3l1x I think this is good enought reason to drop standalone installation of phpstan as it could cause unpredictable errors.
But there two alternative sollutions.
- Use phpstan with roave/better-reflection with which are analysed files not loaded by php itself. But it is much slower and I don't know if it is already possible and free. Main reason for better-reflection is support for legacy aplication and their support will be paid (Ondřej Mirtes talked about it at Posobota)
- Switch to phar version of phpstan because classes inside phar are renamed so they are collision-free

Same as phpstan/phpstan#1456

**Comment by vojtechmares** [comment]
@mabar ok, interesting. I would like to know why `robot-loader` does this kind of mess? Even though phpstan in in different folder, why does `robot-loader` loads the other version?

So far the phpstan-shim looks like a promising solution, but `roave/better-reflection` is probably better in the long run, yet I have not taken second look at the `roave/better-reflection`

Edit: @f3l1x have you considered creating a `contributte` repo where all these coding standard, QA and test things would be stored, so anyone can simply implement them into the project. I think it might help with feature acquistions of new projects/libraries/extensions and we could quite easily keep the track of all contributte's standards. What do you think?

**Comment by mabar** [comment]
It's not directly related to robot-loader, it's just another colliding library. Problem is with native php reflection which do `require file.php` internally so file is not just analysed, it's also loaded by  So problematic would be every single library which is included by project and also by phpstan.

I agree that shim would be best solution for now but it also have it's own downsides. Classes from phpstan vendor are renamed which cause that phpstan extensions cannot use them. At least pepakriz/phpstan-exception-rules don't work with shim.

**Comment by vojtechmares** [comment]
Ok, thank you for the explanation.

Last night I tried the shim, but as you mentioned it has it's own downsites, also another extension which is used does not work: `phpstan/phpstan-deprecation-rules`:

```
$ composer run-script phpstan
> temp/phpstan/vendor/bin/phpstan analyse -l max -c phpstan.neon src

In ContainerBuilder.php line 456:
                                                                               
  Class PHPStan\Rules\Deprecations\AccessDeprecatedPropertyRule used in service 'rules.45' not found.                                                     
                                                                               
analyse [-c|--configuration CONFIGURATION] [-l|--level LEVEL] [--no-progress] [--debug] [-a|--autoload-file AUTOLOAD-FILE] [--error-format ERROR-FORMAT] [--errorFormat ERRORFORMAT] [--memory-limit MEMORY-LIMIT] [--] [<paths>]...
```

**Comment by mabar** [comment]
Did you install shim into same folder as deprecated rules? I think this should work

**Comment by vojtamares** [comment]
Yes, I installed shim into `temp` directory.

composer.json snippet:
```json
{
    “scripts”: 
}
```

**Comment by vojtechmares** [comment]
Yes, I did install it into `temp` directory.

//the close of PR was missclick :/

**Comment by mabar** [comment]
Continues in #20

**Pull request closed without merging**
